- e2e/inference/README.md
Signed-off-by: uMartinXu martin.xu@intel.com
> inference: update README.md

- README.md
Fix typos and clean up the content
`Signed-off-by: Chaitanya <chaitanya.kulkarni@intel.com>`
> Readme: Updated README.md

- nfd/README.md
Optimize and clean up the readme content for clarity. Signed-off-by: Hersh Pathak hersh.pathak@intel.com
> nfd: Update README.md

- kmmo/README.md
Remove 1 bullet point and 1 broken link and update one link to NFD readme. Signed-off-by: Hersh Pathak hersh.pathak@intel.com
> kmmo: Update README.md

- tests/l3/README.md
Added under dev/not supported feature disclaimer in readme
> tests_l3: Update Readme with disclaimer

- tests/README.md
Added under dev/not supported feature disclaimer in tests/ readme
> tests: Update readme with disclaimer

- device_plugins/gpu_device_plugin.yaml
- device_plugins/sgx_device_plugin.yaml
Added custom resource reference yaml files for Intel SGX and Intel GPU
> device_plugins: Added device plugins CR for SGX and GPU

- kmmo/intel-dgpu.yaml
> kmmo: Update container image path to final image published on Red Hat Catalog

- tests/l1/README.md
Update l1 readme with module under development/not supported disclaimer.
The l1 module/feature is not supported in current release.
> tests_l1: Update readme with disclaimer

- device_plugins/README.md
- device_plugins/deploy_gpu.md
- device_plugins/deploy_sgx.md
Updated installation and configuration steps for Intel Device Plugins Operator on OpenShift. Added detailed steps to create Intel SGX and Intel GPU device plugin CRs.
> device_plugins: Updated Readme

- device_plugins/deploy_gpu.md
Fixed typo
signed-off-by: chaitanya1731 <chaitanya.kulkarni@intel.com>
> device_plugins: updated deploy_gpu.md readme

- device_plugins/gpu_device_plugin.yaml
- device_plugins/sgx_device_plugin.yaml
Added Intel Copyright to the CR yaml files
> device_plugins: Updated CR yamls with correct License text

- e2e/inference/README.md
Updated e2e/inference readme for 1.0.0 release
> e2e_inference: Updated Readme for 1.0.0 release

- tests/l2/README.md
Update tests/l2 readme- 'Verifying Intel hardware feature Provisioning' for 1.0.0 release
> tests_l2: Update readme for 1.0.0 release

- machine_configuration/README.md
> machine_configuration: Updated readme

- kmmo/README.md
> kmmo: Updated Readme

- docs/supported_platforms.md
docs/supported_platforms readme
> docs: Added supported_platforms readme

- docs/supported_platforms.md
> docs_supported-platforms: Updated readme

- README.md
Updated root readme links and alignment
> root: Updated root readme links

- e2e/inference/README.md
Updated readme with a link fix
> e2e_inference: Updated readme

- e2e/inference/README.md
Update readme with format changes and links
> e2e_inference: Updated README.md

- device_plugins/deploy_gpu.md
> device_plugins: Fix typo in readme

- machine_configuration/README.md
updated readme links to main branch
> machine_configuration: updated readme links

- nfd/README.md
> nfd: Updated readme links

- tests/l2/README.md
tests_l2: fixed format in readme
> tests_l2: Updated readme

- machine_configuration/100-alternative-fw-path-for-worker-nodes.yaml
> machine_configuration: Add copyright license header

- machine_configuration/README.md
Improving readme quality for clarity.
> machine_configuration: Update README.md

- README.md
> Add Support section in README.md

- kmmo/README.md
> kmmo: Add link to certified driver container

- device_plugins/README.md
> device_plugins: Add link to certified operator

- device_plugins/qat_device_plugin.yaml
> device_plugin: Added QAT plugin reference CR

- device_plugins/README.md
- device_plugins/deploy_qat.md
> device_plugins: Added README for QAT

- nfd/README.md
> nfd: Add QAT to labels table in readme

- README.md
Add OpenVINO and RHODS links for Intel AI inferencing solution section
> Readme: Update readme

- kmmo/intel-dgpu.yaml
> kmmo: Update pre-built GPU driver container image version to 1.1.0

- README.md
> Add QAT feature to readme and bold supported features

- docs/supported_platforms.md
> docs: Add supported OCP version table and BIOS config table

- README.md
Rename link to Supported Intel Hardware Features.
Add link to Supported RHOCP versions 
Add link to reference BIOS config.
> Readme: update root readme

- device_plugins/sgx_device_plugin.yaml
> device_plugins: Update SGX container images path for 1.0.1

- docs/supported_platforms.md
> docs: Updated supported_platforms.md

- device_plugins/deploy_qat.md
> device_plugins: Update deploy_qat readme

- tests/l2/README.md
> tests_l2: Fix indent in readme

- device_plugins/deploy_qat.md
> device_plugins: Updated deploy_qat readme

- device_plugins/README.md
> device_plugins: Updated Readme.md

- machine_configuration/README.md
> machine_configuration: Add registered trademark symbol for Intel QAT

- device_plugins/deploy_qat.md
> device_plugins: Update deploy_qat readme for clarity

- device_plugins/README.md
> device_plugins: Add registered trademark symbols in readme

- device_plugins/install_operator.yaml
> device_plugins: Update operator version for 1.0.1 release

- tests/l2/README.md
Added hwinfo readme details
based on https://github.com/intel/intel-technology-enabling-for-openshift/pull/155
> tests_l2: Update gpu readme for hwinfo

- machine_configuration/README.md
> machine_config: Add steps to verify QAT machine configuration

- nfd/node-feature-discovery-openshift.yaml
> Update NFD image tag for RHOCP 4.13

- kmmo/intel-dgpu.yaml
> kmmo: Update pre-built GPU driver container image version to 2.0.0

- device_plugins/gpu_device_plugin.yaml
- device_plugins/qat_device_plugin.yaml
- device_plugins/sgx_device_plugin.yaml
> device_plugins: Updated container images SHAs for v0.28.0

- device_plugins/install_operator.yaml
> device_plugins: Updated the latest operator version to v0.28.0

- README.md
> Update RHOCP version in Readme

- docs/supported_platforms.md
> docs: Update Supported RHOCP Versions table and links in readme

- nfd/README.md
Remove specific OCP version for easy maintenance.
> nfd: Update RHOCP version links in readme

- kmmo/README.md
> kmmo: Update RHOCP version links in readme

- tests/l2/README.md
Updated RHOCP version and readme links
> tests_l2: Update readme links

- device_plugins/README.md
Update readme about known https://github.com/intel/intel-technology-enabling-for-openshift/issues/113 for 1.1.0 release
> device_plugins: Update readme with known issue

- kmmo/intel-dgpu.yaml
> kmmo: Update driver version to 2.1.0

- kmmo/README.md
KMMv2 updates label name to include namespace.
> kmmo: Update KMM label name used for verification

- .github/workflows/trigger-dci-apps.yml
Added read permissions for the GHA used in the workflow and make it more secure
> workflows: Added read permission to the workflow

- tests/l2/README.md
> tests_l2: Update OCP version links in readme

- machine_configuration/README.md
> machine_configuration: Update OCP version links in readme

- nfd/README.md
> nfd: Update OCP version links in readme

- kmmo/README.md
> kmmo: Update readme with known issue workaround

- README.md
Update RHODS to new name RHOAI
> Root: update readme from RHODS to RHOAI

- README.md
> Readme: Update OCP version and link

- README.md
- docs/releases.md
Added Release Information table for better readability for users
> Root: Update Readme

- docs/releases.md
> docs: Updated releases.md

- kmmo/intel-dgpu.yaml
> kmmo: Update driver version to 2.2.0

- kmmo/README.md
Addresses [#214](https://github.com/intel/intel-technology-enabling-for-openshift/issues/214)
> kmmo: Add section in readme to set FW path at runtime with KMM

- nfd/README.md
> nfd: Add Intel GPU Max series to Labels Table

- kmmo/README.md
Known issue resolved in KMM 2.0.2.
See https://github.com/intel/intel-technology-enabling-for-openshift/issues/194 Signed-off-by: Hersh Pathak hersh.pathak@intel.com
> kmmo: Remove known issue workaround

- docs/supported_platforms.md
Add Intel® Data Center GPU Max Series feature
> supported_platforms: Update Readme

- tests/l2/README.md
- Added support for Flex and Max Series
- Updated hwinfo result for Max Series
> tests_l2: Update readme

- kmmo/README.md
Remove Machine Config prerequisite.
> kmmo: Update readme

- device_plugins/README.md
> device_plugins: Update Readme

- device_plugins/README.md
> device_plugins: Update md in Readme for proper formatting

- device_plugins/README.md
> device_plugins: Remove MCO steps from Readme as no longer using MCO

- docs/releases.md
Updated releases table in readme for ocp 4.15
> docs: Update releases readme for ocp 4.15

- .github/workflows/publish.yml
> Workflow: Added Github Action to Auto-Generate Documentation

- README.md
> Readme: Update root readme markdown formatting

- tests/l2/dgpu/intelvpl_build.yaml
- tests/l2/dgpu/intelvpl_job.yaml
- tests/l2/dgpu/vainfo_build.yaml
- tests/l2/dgpu/vainfo_job.yaml
For L1 test we are using vainfo and for L2 we are using libvpl tests.
> tests_l2: add L1 and L2 test for media feature validation

- tests/README.md
> tests: Updated readme

- tests/l3/README.md
> tests_l3: Update readme

- tests/l2/README.md
Updated l2 tests readme formatting
> tests_l2: Update readme formatting

- device_plugins/deploy_qat.md
> device_plugins: Fixed broken anchor links in readme

- docs/releases.md
- e2e/inference/README.md
> Documentation: Updated Readmes to fix broken links

- tests/l2/dgpu/README.md
> Documentation: add documentation about Intel DGPU media feature L1 and L2 tests

- device_plugins/install_operator.yaml
> device_plugins: Updated Operator Version to install using CLI

- one_click/README.md
- one_click/gpu_provisioning_playbook.yaml
> ansible: Added inital playbook code

- device_plugins/gpu_device_plugin.yaml
- device_plugins/qat_device_plugin.yaml
- device_plugins/sgx_device_plugin.yaml
Signed-off-by: chaitan1731 <chaitanya.kulkarni@intel.com>
> device_plugins: Updated container images SHAs for v0.29.0

- index.rst
> documentation: Updated documentation layout

- docs/releases.rst
Update releases.rst for 1.30 release
> docs_releases: Update release table for 1.3.0

- e2e/inference/README.md
- kmmo/README.md
- machine_configuration/README.md
- nfd/README.md
- one_click/README.md
> documentation: Updated Readme Formatting

- one_click/README.md
Signed-off-by: chaitan1731 <chaitanya.kulkarni@intel.com>
> one_click: Removed note admonition

- device_plugins/README.md
- device_plugins/deploy_gpu.md
- device_plugins/deploy_qat.md
- device_plugins/deploy_sgx.md
- e2e/inference/README.md
- kmmo/README.md
- machine_configuration/README.md
- nfd/README.md
- tests/l2/dgpu/README.md
- tests/l2/qat/README.md
- tests/l2/sgx/README.md
> Updated release version v1.3.0

- .github/workflows/publish.yml
> documentation: Added v1.3.0 release information

- gaudi/README.md
- gaudi/gaudi_device_config.yaml
- gaudi/gaudi_firmware_path.yaml
- gaudi/gaudi_install_operator.yaml
- gaudi/gaudi_nfd_instance_openshift.yaml
> gaudi: Added Gaudi Provisioning on OpenShift details

- gaudi/README.md
- one_click/README.md
- one_click/gaudi_provisioning_playbook.yaml
> one-click: Add Gaudi one-click Provisioning

- index.rst
> documentation: Added Gaudi documentation

- docs/releases.rst
> docs: updated release table for 1.3.1

- workloads/opea/chatqna/README.md
- workloads/opea/chatqna/chatqna_megaservice_buildconfig.yaml
- workloads/opea/chatqna/chatqna_megaservice_deployment.yaml
- workloads/opea/chatqna/create_megaservice_container.sh
- workloads/opea/chatqna/persistent_volumes.yaml
- workloads/opea/chatqna/redis_deployment_service.yaml
- workloads/opea/chatqna/tgi_gaudi_servingruntime.yaml
Added opea-chatqna workload yaml's for rhoai/setup on ocp and readme.
Updated e2e/inference/readme with Intel Gaudi accelerator profile details
> workloads: Added opea-chatqna workload yaml's & readme

- README.md
> README: updated with opea workloads readme link

- workloads/opea/chatqna/README.md
- workloads/opea/chatqna/create_megaservice_container.sh
> workloads_opea: minor fixes for readme links and shell script

- .github/workflows/publish.yml
> documentation: Added doc for release v1.3.1

- gaudi/gaudi_device_config.yaml
> gaudi: Updated DeviceConfig CR with latest v1.17.1 gaudi base operator release

- gaudi/README.md
> gaudi: Updated README to transition from HabanaAI Operator to Intel Gaudi Base operator

- one_click/README.md
- one_click/gaudi_provisioning_playbook.yaml
> one_click: Updated Gaudi provisioning details

- gaudi/gaudi_device_config.yaml
> gaudi: Update DeviceConfig with correct image tag

- nfd/README.md
Update readme links and add DSA to Labels table
> nfd: Update Readme

- kmmo/README.md
> kmmo: Update OCP links in readme

- tests/gaudi/l2/README.md
- tests/gaudi/l2/hccl_build.yaml
- tests/gaudi/l2/hccl_job.yaml
> tests: Added Gaudi HCCL Demo L2 Test Case

- tests/gaudi/l2/README.md
- tests/gaudi/l2/hl-smi_job.yaml
> tests: Added hl-smi Gaudi Test Case

- device_plugins/dsa_device_plugin.yaml
- device_plugins/gpu_device_plugin.yaml
- device_plugins/install_operator.yaml
- device_plugins/qat_device_plugin.yaml
- device_plugins/sgx_device_plugin.yaml
> device_plugins: Updated SHAs for plugins images for v0.29.1 operator

- tests/l2/dsa/dsa_job.yaml
Added security context for capabilities for job to run with custom scc's capabilities
> tests_l2: update dsa-workload job

- docs/supported_platforms.md
Update OCP version links
Add SGX supported on Xeon 6
Update release version to 1.4.0
> docs: Update supported_platforms Readme

- docs/releases.rst
Update release table for 1.4.0 release
> docs_release: Update release table for 1.4.0 release

- tests/l2/README.md
> tests_l2: updated l2 readme for dsa

- .github/workflows/publish.yml
> documentation: Added v1.4.0 release

- tests/gaudi/l2/hccl_build.yaml
- tests/gaudi/l2/hccl_job.yaml
- tests/gaudi/l2/hl-smi_job.yaml
> tests: Gaudi L2 Tests updated for v1.18.0-524

- docs/releases.rst
> docs: Update release readme for 1.5.0

- device_plugins/README.md
- device_plugins/deploy_dsa.md
- device_plugins/deploy_gpu.md
- device_plugins/deploy_qat.md
- device_plugins/deploy_sgx.md
- e2e/inference/README.md
- gaudi/README.md
- kmmo/README.md
- machine_configuration/README.md
- nfd/README.md
- tests/gaudi/l2/README.md
- tests/l2/dgpu/README.md
- tests/l2/dsa/README.md
- tests/l2/qat/README.md
- tests/l2/sgx/README.md
- workloads/opea/chatqna/README.md
> Update release version v1.5.0

- .github/workflows/publish.yml
> Added documentation for v1.5.0

- gaudi/Gaudi-SPI-Firmware-Upgrade.md
- gaudi/README.md
- gaudi/gaudi_spi_fw_upgrade_build.yaml
- gaudi/gaudi_spi_fw_upgrade_job.yaml
Added Steps to upgrade Gaudi SPI Firmware. 
Reference - https://docs.habana.ai/en/latest/Installation_Guide/Platform_Upgrade_and_Unboxing.html#firmware-verification-and-installation 
> gaudi: Added Upgrade Gaudi SPI Firmware

- tests/l2/dsa/README.md
- tests/l2/qat/README.md
- tests/l2/sgx/README.md
This PR updates the SGX, QAT and DSA test documentation by adding the namespace when looking for the pods and logs from the tests to avoid failures of not finding them.
> Documentation: Update tests documentation

- e2e/inference/README.md
> e2e: Update readme for Gaudi with Intel AI tools

- tests/gaudi/l2/README.md
> tests_gaudi: Fix vllm readme

- gaudi/gaudi_device_config.yaml
> gaudi: Update device config version to 1.18

- gaudi/README.md
> gaudi: Update readme link

- docs/releases.rst
> docs: updated Release Table for v1.5.1 release

- tests/gaudi/l2/README.md
- tests/gaudi/l2/test-pod.yaml
Added test-pod yaml for running curl requests to internal services
Updated readme
> tests_gaudi: Update vllm workload and readme

- gaudi/Gaudi-SPI-Firmware-Upgrade.md
> gaudi: Update firmware readme

- gaudi/Gaudi-SPI-Firmware-Upgrade.md
> gaudi: Update firmware upgrade readme

- device_plugins/README.md
- device_plugins/deploy_dsa.md
- device_plugins/deploy_gpu.md
- device_plugins/deploy_qat.md
- device_plugins/deploy_sgx.md
- e2e/inference/README.md
- gaudi/README.md
- kmmo/README.md
- machine_configuration/README.md
- nfd/README.md
- tests/gaudi/l2/README.md
- tests/l2/dgpu/README.md
- tests/l2/dsa/README.md
- tests/l2/qat/README.md
- tests/l2/sgx/README.md
- workloads/opea/chatqna/README.md
> Update Release version v1.5.1

- .github/workflows/publish.yml
> documentation: Added v1.5.1 Documentation

- gaudi/gaudi_spi_fw_upgrade_build.yaml
- gaudi/gaudi_spi_fw_upgrade_job.yaml
> gaudi: Updated SPI FW to support Gaudi v1.19.1-26

- gaudi/Gaudi-SPI-Firmware-Upgrade.md
> gaudi: updated Gaudi SPI Firmware Upgrade readme

- tests/l2/qat/README.md
update qat readme for namespace instruction
> tests_l2: update qat readme

- device_plugins/deploy_qat.md
Updated QAT device plugin readme for provisioning config options
Resolves https://github.com/intel/intel-technology-enabling-for-openshift/issues/357
> device_plugins: Updated QAT device plugin readme

- docs/releases.rst
> docs: update release table

- tests/gaudi/l2/hccl_build.yaml
- tests/gaudi/l2/hccl_job.yaml
- tests/gaudi/l2/hl-smi-firmware_job.yaml
- tests/gaudi/l2/hl-smi_job.yaml
> test: Updated Gaudi L2 tests to v1.19.1

- .github/workflows/publish.yml
> documentation: Added v1.5.2 documentation

- device_plugins/deploy_qat.md
> device_plugins: update qat readme

- kmmo/README.md
- kmmo/intel-dgpu.yaml
- Update intel data center gpu driver for openshift version to 3.0.0
- Update configmap changes for kmm v2.2.0
- Update `setFirmwareClassPath` to `firmwareHostPath`
> kmmo: Update for driver and kmm changes

- docs/supported_platforms.md
> docs: Updated Supported Platforms Readme

- README.md
> root: Updated Readme

- docs/releases.rst
> docs: Updated Release Readme Table

- device_plugins/README.md
- device_plugins/deploy_dsa.md
- device_plugins/deploy_gpu.md
- device_plugins/deploy_qat.md
- device_plugins/deploy_sgx.md
- e2e/inference/README.md
- gaudi/README.md
- kmmo/README.md
- machine_configuration/README.md
- nfd/README.md
- tests/gaudi/l2/README.md
- tests/l2/dgpu/README.md
- tests/l2/dsa/README.md
- tests/l2/qat/README.md
- tests/l2/sgx/README.md
- workloads/opea/chatqna/README.md
> version: Updated version links for v1.6.0 release

- .github/workflows/publish.yml
> documentation: Added v1.6.0 Documentation

- docs/releases.rst
> docs: Update releases.rst

- tests/l2/sgx/README.md
- tests/l2/sgx/sgx_build.yaml
- tests/l2/sgx/sgx_imagestream.yaml
Decoupling imagestream and buildConfig for easier CI integration with Ansible automation
> tests: Decoupling imagestream and buildconfig for SGX for automation

- security/dsa_roleBinding.yaml
> security: Added missing Namespace field in RoleBinding for DSA

- kmmo/README.md
> kmmo: update 4.18 ocp urls

- README.md
> readme: update ocp 4.18 links

- docs/supported_platforms.md
> docs_supported_platforms: Update 4.18 ocp installation links

- nfd/README.md
> nfd: Update readme ocp 4.18 docs links

- device_plugins/README.md
- device_plugins/deploy_dsa.md
- device_plugins/deploy_gpu.md
- device_plugins/deploy_qat.md
- device_plugins/deploy_sgx.md
- e2e/inference/README.md
- gaudi/README.md
- kmmo/README.md
- machine_configuration/README.md
- nfd/README.md
- tests/gaudi/l2/README.md
- tests/l2/dgpu/README.md
- tests/l2/dsa/README.md
- tests/l2/qat/README.md
- tests/l2/sgx/README.md
- workloads/opea/chatqna/README.md
> Updated release version v1.6.1
