intel/intel-technology-enabling-for-openshift

kmmo/intel-dgpu-on-premise-build-mode.yaml

Set `.spec.moduleLoader.container.imagePullPolicy` to `Always` so KMM will always pull the latest image that is built by on-premise mode.
For more details about image pull policy, visit https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting

kmmo: Set imagePullPolicy to Always in on-premise build mode module

---

tests/l2/dgpu/clinfo_build.yaml

This PR updates tests/l2/dgpu/clinfo_build  yaml with:
- clinfo, ocl_icd latest versions with its rpm links
- intel graphics driver repo for RHEL 8.6
- clean up for image (dnf clean)

tests_l2: Update gpu build package versions

---

tests/l2/sgx/sgx_build.yaml
tests/l2/sgx/sgx_job.yaml

- Update linux sgx version from 2.18.1 to [latest 2.19](https://github.com/intel/linux-sgx/releases/tag/sgx_2.19)
- Optimize workdir for sgx build
- Change imagepullpolicy to always- always pulls latest image (In case image present on node and has changed)
- Verified on 4.12.6

tests_l2: Update sgx l2 test

---

nfd/node-feature-rules-openshift.yaml

Keep node feature rules only for SGX, QAT, and GPU.
Keep only 4xxx device IDs for QAT as we support QAT only on SPR or later platforms.

nfd: Update node-feature-rules-openshift.yaml

---

machine_configuration/100-intel-qat-intel-iommu-on.yaml

machine_config: set intel_iommu=on for the worker nodes with QAT device

machine_config: Use default worker pool and NFD QAT label for QAT machine config

---

machine_configuration/100-intel-qat-intel-iommu-on.yaml

machine_configuration: remove extra "`" character in QAT machine config yaml

---

device_plugins/gpu_device_plugin.yaml
device_plugins/qat_device_plugin.yaml
device_plugins/sgx_device_plugin.yaml

Updated SHAs for SGX, GPU and QAT device plugins and initcontainer images for 1.0.1 release

device_plugins: Updated container image SHAs for 1.0.1 release

---

machine_configuration/100-intel-qat-intel-iommu-on.yaml

machine_configuration: Load vfio-pci driver at boot via kernel boot Parameters
Signed-off-by: Manish Regmi <manish.regmi@intel.com>

machine_configuration: add MCO to load vfio-pci driver at boot

---

tests/l2/README.md

Added qatlib workload section based on https://github.com/intel/intel-technology-enabling-for-openshift/pull/117 https://github.com/intel/intel-technology-enabling-for-openshift/pull/132
Fixed typos 

tests_l2: Update readme

---

tests/l2/qat/qatlib_build.yaml
tests/l2/qat/qatlib_job.yaml

tests_l2: Add qatlib based Intel QAT sample workload
- qatlib is built from source in https://github.com/intel/qatlib
- The qatlib version is specified by QATLIB_VERSION: 23.08.0
- cpa_sample_code shipped with qatlib is used to verify the QAT provisioning on OCP
Resources:
- qat.intel.com/dc is used for QAT compression/decompression
- qat.intel.com/cy is used for QAT asymmetric/asymmetric cryptography
- serviceAccount: intel-qat uses the user defined SCC intel-qat-scc which enables the IPC_LOCK capability for Qat-lib based workload see https://github.com/intel/intel-technology-enabling-for-openshift/issues/122
Signed-off-by: [veenadhari.bedida@intel.com](mailto:veenadhari.bedida@intel.com)

tests_l2: Added qat workload

---

device_plugins/qat_device_plugin.yaml

Since We only support 4xxx qat devices, remove unsupported device. Set maxNumDevices to 128.
Signed-off-by: Manish Regmi <manish.regmi@intel.com>

QAT: remove c6xxx and fix maxNumDevices

---

security/qatlib_rbac.yaml

security: Add qatlib rbac yaml to use custom SCC for IPC_LOCK and running container as root
refer to https://github.com/intel/intel-technology-enabling-for-openshift/pull/132

security: Added qatlib_rbac.yaml

---

security/qatlib_scc.yaml

Security: Adding intel-qat-scc for Intel QAT based workload
This user-defined SCC is based on the [OCP predefined restricted-v2 SCC](https://docs.openshift.com/container-platform/4.12/authentication/managing-security-context-constraints.html#default-sccs_configuring-internal-oauth)
The IPC_LOCK capability and RunAsAny permission are added to the restricted-v2 SCC for intel-qat-scc
This patch is used to fix https://github.com/intel/intel-technology-enabling-for-openshift/issues/122

Security: Adding intel-qat-scc for Intel QAT based workload

---

tests/l2/README.md

Update readme with qatlib workload commands based on https://github.com/intel/intel-technology-enabling-for-openshift/pull/137 and https://github.com/intel/intel-technology-enabling-for-openshift/pull/132

tests_l2: Update qat workload commands in readme

---

tests/l2/dgpu/hwinfo_build.yaml
tests/l2/dgpu/hwinfo_job.yaml

Added GPU hwinfo ubi9 based workload for OCP 4.13
Based on [driver verification](https://dgpu-docs.intel.com/driver/installation.html#verify-install)

tests_l2: Added gpu hwinfo workload

---

tests/l2/sgx/sgx_build.yaml

- updated to ubi9.2 for rhel 9.2 on ocp 4.13
- sgx sdk and psw versions to latest 2.22 for rhel 9.2
- changed sgx psw url to match sgx sdk source url

tests_l2: updated sgx build to ubi9

---

machine_configuration/README.md

Disable the in-tree i915 and intel_vsec configuration so KMM can modprobe the
OOT drivers.
This is the short-term solution. In the long-run, the in-tree drivers unload should be handled by KMM operator.

machine_configuration: Update readme

---

tests/l2/README.md
tests/l2/qat/qatlib_build.yaml
tests/l2/qat/qatlib_job.yaml

- Updated qatlib buildconfig to ubi9 with rpm package instead of building from source
- Updated buildconfig, readme to use redhat account credentials for subscription-manager to install rpm packages from specific repos
- qatlib job command updated
- enhancements of entitlement builds and secret build inputs will be added in further releases

tests_l2: Update qatlib workload to ubi9 rpm packages

---

e2e/inference/README.md

e2e_inferece:  Update readme links

---

docs/supported_platforms.md

iOCP release 1.1.0 supports only RHOCP 4.13

docs: Update Supported RHOCP Versions table

---

e2e/inference/README.md

update about https://github.com/intel/intel-technology-enabling-for-openshift/issues/107

e2e_inference: update readme with known issue

---

tests/l2/README.md

Remove GPU workload workaround for https://github.com/intel/intel-technology-enabling-for-openshift/issues/107. Issue fixed in >= OCP 4.14.11 version

tests_l2: Remove workaround for fixed issue #107

---

device_plugins/README.md

Remove workaround for https://github.com/intel/intel-technology-enabling-for-openshift/issues/113. Issue fixed in >= OCP 4.14.10 version. Refer to https://issues.redhat.com/browse/OCPBUGS-20022 for OCP 4.13 and 4.14 details

device_plugins: Remove workaround for fixed issue #113

---

e2e/inference/README.md

Updated e2e readme
- Red Hat OpenShift Data Science (RHODS) operator name to RedHat OpenShift AI (RHOAI)
- Remove workaround for for fixed issue #107. Addressed in #201 and issue fixed in OCP >= 4.14.11
- RHODS dashboard to RHOAI dashboard in doc
- documentation links

e2e: Update readme

---

kmmo/intel-dgpu-on-premise-build.yaml

Update module name and namespace to be <= 40 characters as required by KMM v2. Update filename to match shorter module name.

kmmo: Update intel-dgpu-on-premise-build module and filename

---

tests/l2/dgpu/clinfo_build.yaml

- updated to ubi9 for rhel9 on ocp 4.13
- clinfo and ocl-icd versions for rhel9
- updated intel gpu repo for rhel9 based on [documentation](https://dgpu-docs.intel.com/driver/installation.html#red-hat-enterprise-linux-package-repository)

tests_l2: updated gpu clinfo build to ubi9

---

kmmo/intel-dgpu.yaml

Use KMM feature to remove in-tree intel_vsec at runtime. See link for more details: https://openshift-kmm.netlify.app/documentation/deploy_kmod/#replacing-an-in-tree-module Signed-off-by: Hersh Pathak hersh.pathak@intel.com

kmmo: Remove in-tree module at runtime with KMM

---

e2e/inference/README.md

Remove Machine Config prerequisite- no longer a dependency for Intel GPU from 1.2.1 release

e2e_inference: Update readme

---

kmmo/intel-dgpu.yaml

Load the mei driver which is required to support the media feature. But before loading make sure the in-tree media driver is unloaded. modprobing mei_gsc load all other necessary media drivers.

kmmo: load mei driver for media support

---

kmmo/intel-dgpu-on-premise-build.yaml

Use KMM feature to remove in-tree intel_vsec at runtime. See link for more details: https://openshift-kmm.netlify.app/documentation/deploy_kmod/#replacing-an-in-tree-module Signed-off-by: Hersh Pathak hersh.pathak@intel.com

 kmmo: Remove in-tree module at runtime with KMM on premise build mode

---

nfd/node-feature-rules-openshift.yaml

Use explicit openshift-nfd namespace instead of implicit namespace which can vary based on which project user creates the CR. Signed-off-by: Hersh Pathak hersh.pathak@intel.com

nfd: Add namespace for NodeFeatureRule

---

_templates/versions.html
conf.py

We excluded the old releases - `['v1.0.0', 'v1.0.1','v1.1.0', 'v1.2.0', 'v1.2.1']` from the documentation as we focus on the upcoming `v1.3.0` and above releases. 

Documentation: Added versions dropdown for released Tags

---

nfd/node-feature-discovery-openshift.yaml
nfd/node-feature-rules-openshift.yaml

Fixes https://github.com/intel/intel-technology-enabling-for-openshift/issues/255 
Removed SGX `extraLabelNs` and `resourceLabels` from NodeFeatureDiscovery CR. Added SGX EPC as  
```
extendedResources:
sgx.intel.com/epc: "@cpu.security.sgx.epc" 
```
in the NodeFeatureRule CR.
With these changes, initContainer in SGXDevicePlugin CR wont be used (in Intel device plugins 0.29.0)

nfd: Update NFD CR's to support SGX EPC

---

tests/l2/sgx/sgx_build.yaml

Update l2 tests sgx build's sgx sdk version to 2.24

tests_l2: Update sgx build's sgx sdk version to 2.24

---

e2e/inference/README.md
e2e/inference/accelerator_profile_flex140.yaml
e2e/inference/accelerator_profile_gaudi.yaml

- Updated e2e inference readme for Intel Gaudi accelerator profile details. 
- Added Intel Gaudi accelerator profile.yaml.
-  Updated Flex 140  accelerator profile.yaml name.

e2e_inference: Added Intel Gaudi acceleratorprofile & updated readme

---

nfd/node-feature-rules-openshift.yaml

Add NFD rule for DSA. Its based on PCI device id: 0b25 and in-tree driver idxd

nfd: add nfd rule for DSA

---

nfd/node-feature-discovery-openshift.yaml

updated node feature discovery image to 4.16 for 1.4.0 release

nfd: update node feature discovery image to 4.16

---

e2e/inference/accelerator_profile_gaudi.yaml

updated Intel Gaudi accelerator profile yaml to avoid upper case in the name for RHOAI

e2e_inference: update accelerator profile for Intel Gaudi

---

machine_configuration/100-intel-iommu-on.yaml

DSA requires sm_on to work properly. sm_on enables the IOMMU scalable mode.
This scalable mode is needed by DSA. More details on: https://cdrdv2-public.intel.com/759709/353216-data-streaming-accelerator-user-guide-003.pdf
We also removed qat from name as its used more multiple intel hardwares

MCO: add SVA support to iommu kernel boot parameters

---

README.md
docs/supported_platforms.md

- Removed supported rhocp verison table from supported_platforms readme. This is covered in release readme
- Removed this section link from main readme

docs_supported_platforms: Updated readme

---

tests/gaudi/l2/README.md
tests/gaudi/l2/hccl_build.yaml
tests/gaudi/l2/hccl_job.yaml
tests/gaudi/l2/hl-smi_job.yaml

Updating the namespace to a generic namespace to run all workloads. This helps with easier implementation of one-click solution with ansible.

tests_gaudi: Updated namespace generic name to test gaudi workloads

---

tests/gaudi/l2/README.md

This PR updates the gaudi test documentation by adding as part of the command the namespace when looking for the pods and their logs in order to avoid failures of not finding them.

tests_gaudi: Update gaudi test documentation

---

tests/gaudi/l2/README.md
tests/gaudi/l2/vllm_buildconfig.yaml
tests/gaudi/l2/vllm_deployment.yaml
tests/gaudi/l2/vllm_hf_secret.yaml

PR includes gaudi l2 vllm workload
- buildconfig docker image is based on PR https://github.com/HabanaAI/vllm-fork/pull/602
- deployment including secret for hugging face token and pvc for model cache 
- Readme steps to build, deploy and verify

tests_gaudi: Added L2 vllm workload

---

tests/gaudi/l2/vllm_deployment.yaml

Added copyright 
Added liveness probe in deployment according to [vllm documentation](https://docs.vllm.ai/en/latest/serving/deploying_with_k8s.html)

tests_gaudi: Update vllm deployment

---

tests/gaudi/l2/vllm_buildconfig.yaml

Updated vllm build for 1.19
- gaudi base image- vault.habana.ai/gaudi-docker/1.19.1/rhel9.4/habanalabs/pytorch-installer-2.5.1:1.19.1-26
- habana gaudi version 1.19.1
- vllm habana release v0.6.4.post2+Gaudi-1.19.0

tests_gaudi: Update vllm build for Gaudi 1.19.1

---

tests/gaudi/l2/README.md
tests/gaudi/l2/vllm_buildconfig.yaml

- updated vllm buildconfig git ref to branch  v1.19.1, includes fix https://github.com/HabanaAI/vllm-fork/pull/727
- Readme instructions updated

tests_gaudi: update vllm workload for 1.19.1

---

tests/l2/dgpu/intelvpl_job.yaml

https://github.com/intel/intel-technology-enabling-for-openshift/tree/main/tests/l2/dgpu#using-libvpl this workload does not require any scc or rbac, so service account can be removed

tests_l2: remove unused service account for vpl dsa workload

---

playbooks/README.md
playbooks/configure_nfd.yaml
playbooks/install_device_plugins_operator.yaml
playbooks/install_nfd_operator.yaml
playbooks/intel_ocp_provisioning.yaml

playbooks: Added Initial Ansible Playbooks

---

device_plugins/deploy_qat.md

Updated the example with two labels for 2 CRs respectively

device_plugins: update QAT multiple CRs readme section

---

tests/l2/sgx/sgx_build.yaml

tests_l2: update sgx sdk to 2.26 and image to ubi 9.4

tests_l2: update sgx sdk to 2.26
